Update debugs_self.py
i think __self.results__ instead of __results__ no?


```
Traceback (most recent call last):
  File "/opt/cuckoo-modified/utils/../lib/cuckoo/core/plugins.py", line 414, in run
    result = sig.on_call(call, proc)
  File "/opt/cuckoo-modified/utils/../modules/signatures/debugs_self.py", line 37, in on_call
    for proc in results["behavior"]["processes"]:
NameError: global name 'results' is not defined
```